name: sisifus
channels:
  - defaults
dependencies:
  - python==3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - matplotlib
  - tqdm
  - scikit-image
  - natsort
  - opencv
  - ipykernel
  - scikit-learn
  - ipympl
  - numpy
  - numba
  - conda-forge::pathos
  - spyder
  - pip: 
   - tensorflow==2.10.1
